Update README.md
There is no `hardening` cookbook, it is called `os-hardening`.

This fixes the following error message:
```
Error: Failed to generate Policyfile.lock
Reason: (Solve::Errors::NoSolutionError) Unable to satisfy the following requirements:

- `example-app (>= 0.0.0)` required by `user-specified dependency`
```